create table if not exists companies (id text primary key, ticker text not null unique, name text not null, sector text not null, status text not null check (status in ('active','monitoring','paused')));
create table if not exists triggers (id text primary key, company_id text not null references companies(id), type text not null, detected_at timestamptz not null, severity text not null, summary text not null);
create table if not exists agent_decisions (id text primary key, trigger_id text not null references triggers(id), action text not null, priority text not null, rationale text not null, created_at timestamptz not null);
create table if not exists skore_jobs (id text primary key, company_id text not null references companies(id), status text not null check (status in ('queued','started','completed','failed')), queued_at timestamptz not null, started_at timestamptz, completed_at timestamptz, error text, score numeric, factors jsonb not null default '[]'::jsonb);
create table if not exists reports (id text primary key, company_id text not null references companies(id), score numeric not null, factors jsonb not null default '[]'::jsonb, generated_at timestamptz not null, report_url text);
create table if not exists research_briefs (company_id text primary key references companies(id), summary text not null, why_it_matters text not null, affected_factors jsonb not null default '[]'::jsonb, watch_next jsonb not null default '[]'::jsonb, evidence jsonb not null default '[]'::jsonb);

insert into companies (id,ticker,name,sector,status) values
('c1','NVDA','NVIDIA Corporation','Semiconductors','active'),('c2','MSFT','Microsoft Corporation','Software & Cloud','monitoring'),('c3','JPM','JPMorgan Chase & Co.','Financial Services','active'),('c4','NEE','NextEra Energy','Utilities','paused'),('c5','LLY','Eli Lilly and Company','Healthcare','active') on conflict (id) do nothing;
insert into triggers (id,company_id,type,detected_at,severity,summary) values
('t1','c1','Earnings revision','2026-09-05T08:42:00Z','high','Consensus FY27 EPS estimate moved +8.4% after channel check.'),('t2','c3','Credit spread','2026-09-05T07:58:00Z','medium','Senior debt spread widened 14 bps versus financials basket.'),('t3','c2','Regulatory filing','2026-09-04T16:24:00Z','low','New AI infrastructure capex disclosure in 10-Q amendment.'),('t4','c4','Data quality','2026-09-04T14:11:00Z','critical','Fundamental feed delayed; automated scoring paused.') on conflict (id) do nothing;
insert into skore_jobs (id,company_id,status,queued_at,started_at,completed_at,error,score,factors) values
('job-1042','c1','started','2026-09-05T08:45:00Z','2026-09-05T08:46:00Z',null,null,87,'[{"name":"Earnings momentum","impact":14,"weight":0.3},{"name":"Valuation","impact":-4,"weight":0.25}]'),('job-1041','c3','queued','2026-09-05T08:01:00Z',null,null,null,null,'[{"name":"Credit quality","impact":-8,"weight":0.35}]'),('job-1040','c2','completed','2026-09-04T16:26:00Z','2026-09-04T16:27:00Z','2026-09-04T16:31:00Z',null,74,'[{"name":"Cloud growth","impact":11,"weight":0.35}]'),('job-1039','c4','failed','2026-09-04T14:12:00Z','2026-09-04T14:13:00Z',null,'Fundamental feed unavailable after 3 retries.',null,'[]') on conflict (id) do nothing;
